### PR TITLE
Drop support for EOL Python 2.7

### LINKED ISSUE #402: Drop python 2 support
It's time to remove python 2 support.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #402.

Python 3.5 is also now EOL since 2020-09-03, maybe drop that too?

### CODE REVIEW

**Comment by hugovk** [comment]
@marksweb Ah sorry, didn't spot you'd self-assigned #402, and have a WIP. Feel free to close/merge/re-use parts of this, or I can also have a quick check through after yours is merged. Thanks!

**Comment by marksweb** [comment]
@hugovk No need for apologies. I just thought that I might end up working through this one because I wasn't sure if people were watching the project or what the kind of pace of change might be because I've only just started to help out.

Thank you very much for this, I got a little bit done yesterday, but it looks like you've nailed it & beaten me to the PR so I'll abandon what I'd done.

**Comment by marksweb** [comment]
Oh and yeah, dropping 3.5 is good with me. I was going to look into the dates on 3.x versions so please add that to this change 👍  @hugovk

**Comment by hugovk** [comment]
Updated!

**Pull request merged**
