### PR TITLE
Fix for #483

### PR DESCRIPTION
**Pull request by spapas**
I actually had to create the PR because I needed to use that instead of the pypi release on my requirements to avoid the bad migration.

### CODE REVIEW

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
Thanks @spapas, I thought this was in already 🤦

**Comment by marksweb** [comment]
@spapas could you please add this to the unreleased section in the history file please?

**Comment by spapas** [comment]
@marksweb done (sorry but I couldn't make the link to the PR work)

**Comment by marksweb** [comment]
> @marksweb done (sorry but I couldn't make the link to the PR work)

No problem - I can do that. For reference, the link locations are all at the end of the file and then they just get the syntax added to get them to use that location.

**Comment by spapas** [comment]
Ah!!! I thougth that this was some github magic... Yes I only now noticed the .rst extension :) Thank you!

**Pull request merged**
