### PR TITLE
Issue 174 -  add EXPLORER_SCHEMA_INCLUDE_APPS setting

### PR DESCRIPTION
**Pull request by jproffitt**
This adds the `EXPLORER_SCHEMA_INCLUDE_APPS` to optionally include only a small number of apps in the schema helper.

### CODE REVIEW

**Comment by chrisclark** [comment]
Kudos for the completeness -- both in tests and the readme. Could you rebase to master now that I merged #217 ? Thanks!

**Comment by jproffitt** [comment]
Well, I tried rebasing, but I apparently I did something wrong.

**Comment by jproffitt** [comment]
Ok, I think I fixed it now.

**Comment by chrisclark** [comment]
High-five!

**Pull request merged**
