### PR TITLE
fix extra space around sql

### PR DESCRIPTION
**Pull request by fearless0307**

### CODE REVIEW

**Comment by marksweb** [comment]
What's the actual fix here @fearless0307?

It looks like the markup is the same, just with added line breaks 😂

**Comment by fearless0307** [comment]
@marksweb 
if we use <p> tag, it ignore surrounded space, but if we use <pre> tag, it also consider the surrounded space.
Same issue was here, <textarea> tag was taking surrounded space as value in codemirror editor.

**Comment by marksweb** [comment]
@fearless0307 ah yes I thought that might be why the formatting alone fixed it 👍

Great work. As always I assumed it more complicated & thought it was a problem in the JS!

**Comment by marksweb** [comment]
Released in 2.4.1

https://pypi.org/project/django-sql-explorer/

**Pull request merged**
