### PR TITLE
Use Django's cookie name setting instead of hardcoded name

### PR DESCRIPTION
**Pull request by MounirMesselmeni**
When some one uses custom csrf cookie name in Django, it needs to override the explorer base.html and js files to make it work.
Default Django CSRF cookie name is csrftoken, it can be changed via settings and if so third party apps should support it out of the box.

### CODE REVIEW

**Comment by Anton-Shutik** [comment]
@MounirMesselmeni What's up ? Any description on the PR ?

**Comment by MounirMesselmeni** [comment]
@Anton-Shutik When some one uses custom csrf cookie name in Django, it needs to override the explorer base.html and js files to make it work.
Default Django CSRF cookie name is `csrftoken`

**Comment by Anton-Shutik** [comment]
@MounirMesselmeni Cool, can we add setting description [here](https://github.com/groveco/django-sql-explorer#settings) so people know about that ?

I'd also love to see some tests on that

Thanks for contributing!

**Comment by marksweb** [comment]
@MounirMesselmeni Looking at this, it'd be good to get it merged 👍

**Comment by chrisclark** [comment]
Looks good to me. @marksweb feel free to resolve conflicts and merge! Thanks!

**Comment by MounirMesselmeni** [comment]
@marksweb I updated the PR and added tests. For adding doc about the setting I don't think it's necessary as we will just use the default Django settings for that. Nothing specific for explorer app.

**Comment by marksweb** [comment]
@MounirMesselmeni Excellent work, we do love extra tests!

**Pull request merged**
