### PR TITLE
Upgrade for Django 3 deprecations

### LINKED ISSUE #375: Doesn't run due to bad import "Render_to_response"
ImportError: cannot import name 'render_to_response' from 'django.shortcuts' (/usr/local/lib/python3.7/site-packages/django/shortcuts.py)

Maybe this should be removed?

### LINKED ISSUE #376: Django 3 support
Please add support of Django 3

### PR DESCRIPTION
**Pull request by rob-deutsch**
Fixes #375 
Fixes #376

### CODE REVIEW

**Comment by dannluciano** [comment]
@rob-deutsch thanks man

**Comment by Anton-Shutik** [comment]
@rob-deutsch Would you mind adding django3 to travis conf, so we can make sure tests are passing for django3 ?

**Comment by Anton-Shutik** [comment]
@rob-deutsch What do think about adding django 3 to travis config ?

**Comment by rob-deutsch** [comment]
@Anton-Shutik unfortunately I'm not familiar with Travis, and I don't have capacity this week to learn it

**Comment by Anton-Shutik** [comment]
@rob-deutsch  It should [pretty easy](https://github.com/groveco/django-sql-explorer/blob/master/.travis.yml), just add one more line with django 3

**Comment by marksweb** [comment]
@rob-deutsch Could you take a look at the conflict on this please?

I'm looking at getting bits merged ready for a new release.

**Pull request merged**
