### PR TITLE
Improved templates to make easier to customize them for integration w…

### PR DESCRIPTION
**Pull request by nad2000**
Fix for #477:
- added _block.super_ to reuse base block;
- following admin convention added block "_extrastyle_" to facilitate customization;

### CODE REVIEW

**Review by marksweb — CHANGES_REQUESTED** [review]
The call to super seems unnecessary as the block in base is empty so won't pull anything in?

**Comment by nad2000** [comment]
@marksweb it's done so that customization can be done in one place - the explorer/base.html. Otherwise, you would have to override all 4 templates: query_list.html, query.html, play.html and qyertlog_list.html.

Well here is my explorer/base.html that works with the proposed changes:

```
{% extends "explorer/base.html" %}

{% block extrastyle %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
{% endblock %}

{% block sql_explorer_navlinks %}
  <li class="nav-item" id="admin:index">
    <a id="admin-link"
       class="nav-link"
       href="{% url 'admin:index' %}"
       data-toggle="tooltip"
       title="Research Funding Data Administration"
       >
       <i class="fas fa-radiation"></i> RFDA Admin</a>
  </li>
{% endblock %}


{% block sql_explorer_scripts %}
  <script>
    $(document).ready(function() {
      $('[data-toggle="tooltip"]').tooltip()
    });
  </script>
{% endblock %}
```

and this is how it gets rendered:
image


Without them, I would have to override almost the entire base.html.

**Comment by nad2000** [comment]
Actually, it was possible to refactor and dry a bit the templates and move the sql_explorer_navlinks block to the base.html.

**Comment by marksweb** [comment]
@nad2000 Ok now I get what you're doing so that makes sense 👍 

I'll have a proper look at this over the weekend hopefully 🤞

**Comment by ernstki** [comment]
I'm overriding `explorer/base.html` in our application, just as @nad2000 prescribed [above](https://github.com/chrisclark/django-sql-explorer/pull/478#issuecomment-1185075224), but getting double the nav `<li>`s in the site's rendered output.

I frankly didn't follow the context processor part of the conversation (beyond a vague understanding of what a context processor is), but could that have something to do with this? Or have I just done something boneheaded?

There is only this single file in `myapp/templates/explorer`:

```jinja2
{# myapp/templates/explorer/base.html #}
{% block sql_explorer_navlinks %}
{{ block.super }}
<li><a href="{{ DEFAULT_URL }}/explorer/schema/readonly">Schema</a></li>
<li><a href="#">|</a></li>                                              
<li><a href="{{ DEFAULT_URL }}/admin/">Back to {{ SITE_TITLE }}</a></li>
{% endblock %}
```
Screenshot of the effect described above

I'm currently using `django-sql-explorer==3.2.1`, the latest release as of this writing.

**Comment by nad2000** [comment]
The feature (the template block **sql_explorer_navlinks**) was removed with dc2b783ae253fe9a96d465ee51bdf28ac66e1b12 :(

**Pull request merged**
