### PR TITLE
Add param labels

### PR DESCRIPTION
**Pull request by spapas**
This implements #486.

### CODE REVIEW

**Comment by spapas** [comment]
Hello friends! Any idea when this will be merged or if it may need some changes to be ready? This is a small change and shouldn't break anything. I'm already using my branch on my project and works great and would really like to see this merged on main to avoid adding the github branch on my requirements.

The only thing that may be needed is that if you are embedding queries in your views (see this issue #485 ). You'll need to change the input label and value similar to how they have been implemented in the internal templates. See the diffs on explorer/templates/explorer/params.html (https://github.com/groveco/django-sql-explorer/blob/3d78a805d428cf4a6e5f10a38b1048a9f9b7496a/explorer/templates/explorer/params.html#L6)

But this change would be done in any case to take advantage of the labels. Also I'm not really sure how many people are using this feature since the #485 didn't get any traction :(

Thank you!

**Comment by marksweb** [comment]
@spapas Sorry - I'd missed this PR.

I'm not using the app like this, but can at least take a look at the code and see it makes sense.

It's sometimes a bit frustrating that users aren't more involved on here, because the app does get used by quite a lot of people;
https://pepy.tech/project/django-sql-explorer

**Comment by spapas** [comment]
@marksweb thank you! 

Well no matter how you use the app I think that adding labels to your parameters will improve the use experience. Especially if you want to have nice non-english labels, i.e here's a query I use this with:

```
select aa.id, aa.created_on,
aa.dynamic_data->>'date' as "Ημερμηνία",
aa.dynamic_data->>'authority' as "Υπηρεσία",
aa.dynamic_data->>'mail' as "Email",
aa.dynamic_data
from apps_app aa 
left join apptypes_apptype aat on 
aa.app_type_id = aat.id
where aat.id = 8
and aa.dynamic_data->>'mail' like "%$$email|Email$$%"
and aa.dynamic_data->>'authority' like "%$$authority|Υπηρεσία$$%"
```

i prefer seeing "Υπηρεσία" instead of "authority" :)

**Comment by spapas** [comment]
Hey @marksweb any news about the status of this PR ? 

Thank you!

**Comment by marksweb** [comment]
@spapas I'm waiting for pypi to merge the django 4.2 classifier to get a release together. This will go into that.

**Pull request merged**
