### PR TITLE
Problem importing celery to enable tasks

### PR DESCRIPTION
**Pull request by lawson89**
Issue #493

### CODE REVIEW

**Comment by lawson89** [comment]
@marksweb just checking if any tweaks I need to make to this PR? Thanks!

**Comment by marksweb** [comment]
@lawson89 Sorry, I'd forgotten about this. I will continue my review tomorrow.

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
@lawson89 I've just got finished with pre-commit hooks.

Now this does bring some conflicts with your work here - sorry about that - but I wanted to get these hooks in before any more changes come in. Could you take a look at updating your branch and resolving please?

**Comment by marksweb** [comment]
@lawson89 There's just some linting issues to resolve. You could get isort to fix the imports itself with `isort explorer` then there's just 1 flake8 issue with some indentation I think.

**Comment by lawson89** [comment]
Yep - will take care of those in just a bit

**Comment by lawson89** [comment]
@marksweb - this one should be ready. Once it's merged then I can make the S3 integration more generic per issue #503

**Review by marksweb — APPROVED** [review]

**Pull request merged**
