### PR TITLE
WIP - pdf export

### PR DESCRIPTION
**Pull request by chrisclark**
Not sure how robust this is as data sets get wider and longer -- will have to experiment. Also needs tests. Man...PDFs are a pain.

Issue #207

### CODE REVIEW

**Comment by mykljohn** [comment]
Sure I'll test it...how can I install it, or just copy the code to my exisitng?

**Comment by chrisclark** [comment]
Copying the code will work -- or just put this in your requirements file:

-e git+
https://github.com/groveco/django-sql-explorer@4761bbce8c94b2b20d604b38992b29b89a9016da#egg=explorer

On Wed, Jun 15, 2016 at 4:49 PM, mykljohn <notifications@github.com> wrote:

> Sure I'll test it...how can I install it, or just copy the code to my
> exisitng?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/groveco/django-sql-explorer/pull/208#issuecomment-226352553>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAqVxFf24UM6-_Ck1TXA5qnRMyZERnl6ks5qMI94gaJpZM4I2jKf>
> .
>



-- 

Chris Clark │ Grove Co. │ 617-571-7327

1770 Union St, San Francisco, CA

**Comment by mykljohn** [comment]
Hey, I'm getting this error when I try to syncdb after successful pip install of explorer 0.9.2.  any idea why?
+1: 
 Rendering model states...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command
_line
    utility.execute()
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 100, in migrate
    state.apps  # Render all real_apps -- performance critical
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 166, in apps
    return StateApps(self.real_apps, self.models)
  File "/home/mykl/.virtualenvs/django18/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 248, in __init__
    raise ValueError(msg.format(field=operations[0][1], model=lookup_model))
ValueError: Lookup failed for model referenced by field eval.QueryLog.query: explorer.Query

**Comment by chrisclark** [comment]
See comment in #207 and new PR #248

**Pull request closed without merging**
